import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Home, List, Search, User } from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scrollbar-none">
      <body
        className={`${inter.className} max-w-sm mx-auto bg-foreground relative scrollbar-none`}
      >
        {children}
        <nav className="fixed bottom-0 left-0 right-0 p-4 max-w-sm mx-auto bg-foreground">
          <div className="flex justify-around items-center text-secondary">
            <Home className="w-6 h-6" />
            <Search className="w-6 h-6" />
            <List className="w-6 h-6" />
            <User className="w-6 h-6" />
          </div>
        </nav>
      </body>
    </html>
  );
}
